#When executing docker run for an image with Chrome or Firefox please either mount -v /dev/shm:/dev/shm or use the flag --shm-size=2g to use the host's shared memory.
#example create image: docker build -t jorge2m/robotest:latest .
#example container run: docker run -d -p 80:8080 -p 443:443 --privileged -v "%CD%/dockerresults:/robotest/output-library" jorge2m/robotest:latest
#   -> In PowerShell replace %CD% by ${pwd}
FROM jorge2m/chrome-firefox-openjdk17-maven:1664466494

COPY target/robotest.zip robotest.zip
RUN unzip robotest.zip
	
COPY docker-entrypoint-debug.sh /robotest/docker-entrypoint.sh

RUN apt-get update && \
    apt-get install -y x11vnc && \
    mkdir ~/.vnc && \
    x11vnc -storepasswd 1234 ~/.vnc/passwd     
#RUN sed 's/TLSv1, TLSv1.1,/ /' etc/java-8-openjdk/security/java.security -i
	
WORKDIR /robotest

#Expose port 5900 to view display using VNC Viewer
EXPOSE 5900
EXPOSE 8000
EXPOSE 8080

ENTRYPOINT ["bash","/robotest/docker-entrypoint.sh"]
#CMD echo "none /dev/shm tmpfs defaults,size=2g 0 0" >> /etc/fstab ; mount -o remount /dev/shm ; xvfb-run -s "-screen 0 1024x768x24" java -cp robotest.jar com.mng.robotest.access.rest.ServerRest -port 80 -secureport 443
