//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.09 at 04:51:58 PM CET 
//


package com.mng.robotest.test80.mango.test.factoryes.jaxb.sitemap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mng.robotest.test80.mango.test.factoryes.jaxb.sitemap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry

public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mng.robotest.test80.mango.test.factoryes.jaxb.sitemap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sitemapindex }
     * 
     */
    public Sitemapindex createSitemapindex() {
        return new Sitemapindex();
    }

    /**
     * Create an instance of {@link Sitemapindex.Sitemap }
     * 
     */
    public Sitemapindex.Sitemap createSitemapindexSitemap() {
        return new Sitemapindex.Sitemap();
    }

}
