apiVersion: v1
kind: Service
metadata:
  name: robotest-hub
  namespace: mango
  labels:
    k8s-app: robotest-hub
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
  selector:
    k8s-app: robotest-hub
